### ISSUE TITLE
Incompatible with Microsoft.AspNetCore.OData, Version=8.0.0.0...?

### ISSUE THREAD

**Issue by eric-miller-cdfw** [OData/WebApiAuthorization#5]
It looks like the "core" version of the lib is referencing some .NET Framework API's... Also, the docs don't seem correct for how to configure startup.

Docs show ConfigServices like:
```csharp
services.AddOData()
        .AddAuthorization(options =>
        {
            options.ScopesFinder = context =>
            {
                var userScopes = context.User.FindAll("Scope").Select(claim => claim.Value);
                return Task.FromResult(userScopes);
            };
            options.ConfigureAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie();
        });
```
But the AddAuthorization() extension method seems to be for .NET Framework. So, I tried ...

```csharp
services.AddODataAuthorization(options =>
            {
                options.ScopesFinder = context =>
                {
                    var userScopes = context.User.FindAll("Scope").Select(claim => claim.Value);
                    return System.Threading.Tasks.Task.FromResult(userScopes);
                };
            });
```

And, for authentication, I want to use Azure AD (Bearer tokens)
```csharp
            services.AddMicrosoftIdentityWebApiAuthentication(Configuration);
```

And, in the Configure method:
```csharp
            app.UseAuthentication();
            app.UseODataAuthorization();
```

But, I get the following exception at startup...
```
System.TypeLoadException: Could not load type 'Microsoft.AspNet.OData.Interfaces.IODataFeature' from assembly 'Microsoft.AspNetCore.OData, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.AspNetCore.OData.Authorization.ODataAuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by Firas88Alkhatib** [comment]
WebApi Authorization currently only supports OData WebApi 7.x, AspNet.Core 3.1 with endpoint routing.

refer to :
https://docs.microsoft.com/en-us/odata/webapiauth/overview

**Comment by ekomut** [comment]
Could I ask, do you have any idea, when will development possible?
I do not find any information on microsoft website

**Comment by bytefish** [comment]
@eric-miller-cdfw @Firas88Alkhatib I think this is obviously a duplicate to #9. The referenced PR #13 is an effort to update the library to ASP.NET Core OData 8. If there is still interest, one could try to improve the PR as a community effort and maybe get it accepted.

**Comment by willsmithgithub** [comment]
Could really use this feature.  Seem ODATA is being outpaced by this -  https://learn.microsoft.com/en-us/azure/data-api-builder/overview-to-data-api-builder?tabs=azure-sql  which is a shame as ODATA is much more mature.  The data api supports authorization and more granular (property level).  something this project could add as well.
